# keys
MENDELEY_CLIENT_ID: ${ssm:/zettelkasten/MENDELEY_CLIENT_ID}
MENDELEY_CLIENT_SECRET: ${ssm:/zettelkasten/MENDELEY_CLIENT_SECRET}
DOCALYSIS_CLIENT_ID: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_ID}
DOCALYSIS_CLIENT_SECRET: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_SECRET}
