service: zettelkasten
frameworkVersion: '3'

params:
  default:
  dev:
    salt: SJxV9oNKRtEks8un3W3jUZSkHwrxBOdZ
    jwtSecret: UkBN0me9JRvODL8Olb9iszmWxuOYt74OJEeTfFtiajbTScOGL6iFcMjepagitemzj4DqbHtKV6JokQpdZg8u96EHRUklWoQV3HjSm2PlQdC8hekOlSUWZPTjcMn8DvHdFwkkG7FC63N9yRnHQwAPNuNXNWZfoXlZZNbwirr2t7LLUV5rw9uE8CBEghVQt1KWH9284t5RxmVBtDpSSOs3rITMj6Sh8L9m2tu0KwGszdH45Scl2rce4RIS9Qr8fYS3
  prod:
    # salt: ${ssm:/zettelkasten/salt}
    # jwtSecret: ${ssm:/zettelkasten/jwtSecret}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage}
  deploymentBucket:
    name: zettelkasten-lambda-code-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/zettelkasten-users-${opt:stage}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/zettelkasten-users-${opt:stage}/*
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/zettelkasten-files-${opt:stage}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/zettelkasten-files-${opt:stage}/*

        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::zettelkasten-files-${opt:stage}
            - arn:aws:s3:::zettelkasten-files-${opt:stage}/*
            - arn:aws:s3:::zettelkasten-user-avatar-${opt:stage}
            - arn:aws:s3:::zettelkasten-user-avatar-${opt:stage}/*

  environment:
    SHOW_LOGS: true
    SALT: ${param:salt}
    JWT_SECRET: ${param:jwtSecret}
    REGION: ${self:provider.region}
    FILES_BUCKET: zettelkasten-files-${opt:stage}
    USER_AVATAR_BUCKET: zettelkasten-user-avatar-${opt:stage}
    USERS_TABLE: zettelkasten-users-${opt:stage}
    FILES_TABLE: zettelkasten-files-${opt:stage}
    # MENDELEY_CLIENT_ID: ${ssm:/zettelkasten/MENDELEY_CLIENT_ID}
    # MENDELEY_CLIENT_SECRET: ${ssm:/zettelkasten/MENDELEY_CLIENT_SECRET}
    # DOCALYSIS_CLIENT_ID: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_ID}
    # DOCALYSIS_CLIENT_SECRET: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_SECRET}
    # OBSIDIAN_CLIENT_ID: ${ssm:/zettelkasten/OBSIDIAN_CLIENT_ID}
    # OBSIDIAN_CLIENT_SECRET: ${ssm:/zettelkasten/OBSIDIAN_CLIENT_SECRET}

functions:
  authenticate:
    handler: src/lambda/users.authenticate
    events:
      - httpApi:
          path: /login
          method: post

  createUser:
    handler: src/lambda/users.createUser
    events:
      - httpApi:
          path: /user
          method: post

  getUser:
    handler: src/lambda/users.getUser
    events:
      - httpApi:
          path: /user/{email}
          method: get

  updateUser:
    handler: src/lambda/users.updateUser
    events:
      - httpApi:
          path: /user/{email}
          method: put

  deleteUser:
    handler: src/lambda/users.deleteUser
    events:
      - httpApi:
          path: /user/{email}
          method: delete

  activateUser:
    handler: src/lambda/users.activateUser
    events:
      - httpApi:
          path: /user/activate/{token}
          method: put

  getUnlockToken:
    handler: src/lambda/users.getUnlockToken
    events:
      - httpApi:
          path: /user/unlock/{email}
          method: get

  unlockUser:
    handler: src/lambda/users.unlockUser
    events:
      - httpApi:
          path: /user/unlock
          method: put

  createPreSignedUrl:
    handler: src/lambda/files.createPreSignedUrl
    events:
      - httpApi:
          path: /files/presignedUrl
          method: post

  handleFileUploaded:
    handler: src/lambda/files.handleFileUploaded
    events:
      - s3:
          bucket: zettelkasten-files-${opt:stage}
          event: s3:ObjectCreated:*

