service: zettelkasten
frameworkVersion: '3'

params:
  default:
  dev:
    salt: SJxV9oNKRtEks8un3W3jUZSkHwrxBOdZ
    jwtSecret: UkBN0me9JRvODL8Olb9iszmWxuOYt74OJEeTfFtiajbTScOGL6iFcMjepagitemzj4DqbHtKV6JokQpdZg8u96EHRUklWoQV3HjSm2PlQdC8hekOlSUWZPTjcMn8DvHdFwkkG7FC63N9yRnHQwAPNuNXNWZfoXlZZNbwirr2t7LLUV5rw9uE8CBEghVQt1KWH9284t5RxmVBtDpSSOs3rITMj6Sh8L9m2tu0KwGszdH45Scl2rce4RIS9Qr8fYS3
  prod:
    # salt: ${ssm:/zettelkasten/salt}
    # jwtSecret: ${ssm:/zettelkasten/jwtSecret}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage}
  deploymentBucket:
    name: zettelkasten-lambda-code-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-2:180514372124:table/zettelkasten-users-${self:provider.stage}

  environment:
    SHOW_LOGS: true
    SALT: ${param:salt}
    JWT_SECRET: ${param:jwtSecret}
    REGION: ${self:provider.region}
    FILES_BUCKET: zettelkasten-${opt:stage}
    USERS_TABLE: zettelkasten-users-${opt:stage}
    # MENDELEY_CLIENT_ID: ${ssm:/zettelkasten/MENDELEY_CLIENT_ID}
    # MENDELEY_CLIENT_SECRET: ${ssm:/zettelkasten/MENDELEY_CLIENT_SECRET}
    # DOCALYSIS_CLIENT_ID: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_ID}
    # DOCALYSIS_CLIENT_SECRET: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_SECRET}
    # OBSIDIAN_CLIENT_ID: ${ssm:/zettelkasten/OBSIDIAN_CLIENT_ID}
    # OBSIDIAN_CLIENT_SECRET: ${ssm:/zettelkasten/OBSIDIAN_CLIENT_SECRET}

functions:
  authenticate:
    handler: src/lambda/users.authenticate
    events:
      - httpApi:
          path: /login
          method: post
