service: zettelkasten
frameworkVersion: '3'

params:
  default:
    dbName: zettelkasten
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: SJxV9oNKRtEks8un3W3jUZSkHwrxBOdZ
    jwtSecret: UkBN0me9JRvODL8Olb9iszmWxuOYt74OJEeTfFtiajbTScOGL6iFcMjepagitemzj4DqbHtKV6JokQpdZg8u96EHRUklWoQV3HjSm2PlQdC8hekOlSUWZPTjcMn8DvHdFwkkG7FC63N9yRnHQwAPNuNXNWZfoXlZZNbwirr2t7LLUV5rw9uE8CBEghVQt1KWH9284t5RxmVBtDpSSOs3rITMj6Sh8L9m2tu0KwGszdH45Scl2rce4RIS9Qr8fYS3
  prod:

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  # stage: ${opt:stage}
  # deploymentBucket:
  #   name: zettelkasten-lambda-code-${self:provider.stage}
  environment:
    SHOW_LOGS: true
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param:salt}
    JWT_SECRET: ${param:jwtSecret}
    # FILES_BUCKET: zettelkasten-${opt:stage}
    # MENDELEY_CLIENT_ID: ${ssm:/zettelkasten/MENDELEY_CLIENT_ID}
    # MENDELEY_CLIENT_SECRET: ${ssm:/zettelkasten/MENDELEY_CLIENT_SECRET}
    # DOCALYSIS_CLIENT_ID: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_ID}
    # DOCALYSIS_CLIENT_SECRET: ${ssm:/zettelkasten/DOCALYSIS_CLIENT_SECRET}

functions:
  login:
    handler: /src/lambda/user.authenticate
    events:
      - httpApi:
          path: /login
          method: post

  createUser:
    handler: /src/lambda/user.createUser
    events:
      - httpApi:
          path: /user
          method: post
  
  getUser:
    handler: /src/lambda/user.getUser
    events:
      - httpApi:
          path: /user/{id}
          method: get

plugins:
  - serverless-offline
